name: CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Test simple
        run: echo "CI Pipeline exécuté avec succès pour la PR !"
